apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
replicas:
  - name: argocd-webpage
    count: 1
resources:
  - ../../base
configMapGenerator:
  - name: config
    files:
      - config.txt