apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
replicas:
  - name: argocd-webpage
    count: 3
resources:
  - ../../base
configMapGenerator:
  - name: config
    files:
      - config.txt