name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Building and Publishing the Image
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Push docker image to Docker Hub
      run: docker push ${{secrets.DOCKER_USER}}/argocd-webpage
