name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Building and Publishing the Image
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/argocd-webpage:latest
        platforms: linux/arm64,linux/arm64/v8
